df<- read.csv("/cloud/project/alcohol-consumption.csv")
View(df)
install.packages("tidyverse")
library(tidyverse)
str(df)
colSums(is.na(df))
df<-na.omit(df)
head(df)
dim(df[duplicated(df$country),])[1]
df$wine_percentage <- round(df$wine_percentage ,digit=2)
df$total_consumption <- round(df$total_consumption ,digit=2)
View(df)
dim(df)
library(ggplot2)
ggplot(data=df, aes(x=spirits_percentage, y=country)) +geom_bar(stat="identity")
ggplot(df,aes(x=spirits_percentage, y=wine_percentage)) +geom_boxplot(outlier.colour= "green",outlier.shape= 1)+scale_x_continuous(labels = scales::comma)+coord_cartesian(ylim= c(0,1000))
dim(df)
head(df)
view(df)
drops<- c("profitability")
view(df)
df <-df[ ,!(names(df)%in%drops)]
view(df)
Q1 <- quantile(df$spirits_percentage, .25)
Q3 <- quantile(df$spirits_percentage, .75)
IQR <- IQR(df$spirits_percentage)
no_outliers <- subset(df, df$spirits_percentage> (Q1 - 1.5*IQR) & df$spirits_percentage< (Q3 + 1.5*IQR))
dim(no_outliers)
Q1 <- quantile(df$total_consumption, .25)
quantile(df$total_consumption, .75)
IQR <- IQR(df$total_consumption)         
df2 <- subset(no_outliers, no_outliers$total_consumption> (Q1 - 1.5*IQR) & no_outliers$total_consumption< (Q3 + 1.5*IQR))
dim(df2)
summary(df2)
ggplot(df1, aes(x=country, y=total_consumption)) + geom_point()+ scale_y_continuous(labels = scales::comma)+coord_cartesian(ylim = c(0, 110))+theme(axis.text.x = element_text(angle = 90))
ggplot(df1, aes(x=beer_percentage)) + geom_bar()
write.csv(df2, "clean1_df.csv")
